#!/usr/bin/env python3
"""
Generates the static HTML pages for Kathat Estate from PROPERTIES below.
This script is NOT part of the deliverable — it's how I produced the final
.html files. The output (index.html, properties/*.html, dashboard.html) is
what actually ships, and needs no build step to deploy.
"""
import os

OUT = os.path.dirname(os.path.abspath(__file__))

PROPERTIES = [
    dict(
        slug="bandra-west", cityEn="Mumbai", cityHi="मुंबई",
        areaEn="Bandra West", areaHi="बांद्रा वेस्ट",
        name="Godrej Bandra West", developerEn="Godrej Properties", developerHi="गोदरेज प्रॉपर्टीज",
        taglineEn="Where the sea writes the skyline.", taglineHi="जहाँ समंदर आसमान की कहानी लिखता है।",
        descriptionEn="Spread across 4.25 acres in the heart of Bandra West, Godrej Bandra West brings 2, 3 and 4 BHK residences to one of Mumbai's most storied neighbourhoods — close to the Bandra-Worli Sea Link and a short drive from BKC.",
        descriptionHi="बांद्रा वेस्ट के केंद्र में 4.25 एकड़ में फैला, गोदरेज बांद्रा वेस्ट मुंबई के सबसे प्रतिष्ठित इलाकों में से एक में 2, 3 और 4 बीएचके रेजिडेंस लेकर आता है — बांद्रा-वर्ली सी लिंक के करीब और बीकेसी से थोड़ी दूरी पर।",
        whyInvestEn=["Close to the Bandra-Worli Sea Link, cutting commute to Lower Parel and Worli",
                     "Consistently one of Mumbai's most sought-after addresses, with limited new supply",
                     "Walking distance to Bandra's café culture, Carter Road, and Bandstand promenade",
                     "Short drive from BKC — Mumbai's primary business district"],
        whyInvestHi=["बांद्रा-वर्ली सी लिंक के करीब, लोअर परेल और वर्ली तक का सफर आसान",
                     "नई सप्लाई सीमित होने के कारण मुंबई के सबसे मांग वाले पतों में से एक",
                     "बांद्रा की कैफे संस्कृति, कार्टर रोड और बैंडस्टैंड प्रॉमेनेड से पैदल दूरी",
                     "मुंबई के प्रमुख बिज़नेस डिस्ट्रिक्ट बीकेसी से थोड़ी दूरी"],
        amenitiesEn=["Landscaped podium gardens", "Clubhouse with pool", "Wellness spa & gym", "24-hour concierge & security"],
        amenitiesHi=["लैंडस्केप्ड पोडियम गार्डन", "पूल के साथ क्लबहाउस", "वेलनेस स्पा और जिम", "24 घंटे कॉन्सियर्ज और सुरक्षा"],
        units=[dict(type="2 BHK", typeHi="2 बीएचके", size="740–950", priceCr=3.5),
               dict(type="3 BHK", typeHi="3 बीएचके", size="1,050–1,400", priceCr=5.2),
               dict(type="4 BHK", typeHi="4 बीएचके", size="1,600–2,100", priceCr=8.4)],
        heroArt="tower",
    ),
    dict(
        slug="indiranagar", cityEn="Bengaluru", cityHi="बेंगलुरु",
        areaEn="Indiranagar", areaHi="इंदिरानगर",
        name="Godrej Athena", developerEn="Godrej Properties", developerHi="गोदरेज प्रॉपर्टीज",
        taglineEn="Greco-Roman grandeur, in the heart of Indiranagar.", taglineHi="इंदिरानगर के केंद्र में, ग्रीको-रोमन भव्यता।",
        descriptionEn="Spread over 6.5 acres in the Indiranagar-HAL micro-market, Godrej Athena is a low-rise, Greco-Roman-inspired development of 2, 3 and 3.5 BHK residences — one of East Bengaluru's most distinctive boutique addresses.",
        descriptionHi="इंदिरानगर-एचएएल माइक्रो-मार्केट में 6.5 एकड़ में फैला, गोदरेज एथेना एक लो-राइज़, ग्रीको-रोमन शैली से प्रेरित 2, 3 और 3.5 बीएचके रेजिडेंस का विकास है — पूर्वी बेंगलुरु के सबसे विशिष्ट बुटीक पतों में से एक।",
        whyInvestEn=["In the Indiranagar-HAL micro-market, minutes from Old Airport Road",
                     "Low-rise, boutique-scale development — only a few hundred residences across 6.5 acres",
                     "One of Bengaluru's most consistently high rental-demand micro-markets",
                     "100 Feet Road's restaurants, boutiques, and metro connectivity nearby"],
        whyInvestHi=["इंदिरानगर-एचएएल माइक्रो-मार्केट में, ओल्ड एयरपोर्ट रोड से कुछ ही मिनट",
                     "लो-राइज़, बुटीक स्तर का विकास — 6.5 एकड़ में सीमित रेजिडेंस",
                     "बेंगलुरु के सबसे लगातार उच्च किराया-मांग वाले इलाकों में से एक",
                     "100 फ़ीट रोड के रेस्तरां, बुटीक और मेट्रो कनेक्टिविटी नज़दीक"],
        amenitiesEn=["22,000 sq.ft. clubhouse", "Swimming pool & yoga deck", "Pet park", "Multipurpose sports court"],
        amenitiesHi=["22,000 वर्ग फुट का क्लबहाउस", "स्विमिंग पूल और योगा डेक", "पेट पार्क", "मल्टीपर्पज़ स्पोर्ट्स कोर्ट"],
        units=[dict(type="2 BHK", typeHi="2 बीएचके", size="1,180–1,400", priceCr=2.6),
               dict(type="3 BHK", typeHi="3 बीएचके", size="1,710–1,900", priceCr=3.5),
               dict(type="3.5 BHK", typeHi="3.5 बीएचके", size="2,050", priceCr=3.9)],
        heroArt="tower",
    ),
    dict(
        slug="golf-course-road", cityEn="Gurugram", cityHi="गुरुग्राम",
        areaEn="Golf Course Road", areaHi="गोल्फ कोर्स रोड",
        name="DLF The Camellias", developerEn="DLF Limited", developerHi="डीएलएफ लिमिटेड",
        taglineEn="Mornings that open onto green.", taglineHi="सुबहें जो हरियाली में खुलती हैं।",
        descriptionEn="In Sector 42 on Golf Course Road, DLF The Camellias is among India's most iconic ultra-luxury addresses — lake-facing residences with bungalow-style architecture by Hafeez Contractor, and India's first LEED Platinum-certified residential project.",
        descriptionHi="सेक्टर 42, गोल्फ कोर्स रोड पर, डीएलएफ द कैमेलियास भारत के सबसे प्रतिष्ठित अल्ट्रा-लक्ज़री पतों में से एक है — हाफ़िज़ कॉन्ट्रैक्टर द्वारा बंगला-शैली की वास्तुकला के साथ लेक-फेसिंग रेजिडेंस, और भारत का पहला LEED प्लेटिनम-प्रमाणित रेजिडेंशियल प्रोजेक्ट।",
        whyInvestEn=["India's first LEED Platinum-certified luxury residential project",
                     "Lake-facing residences, bungalow-style design by architect Hafeez Contractor",
                     "Interiors by Rockwell Group (New York); adjoining golf courses by Arnold Palmer and Gary Player",
                     "Among the highest per-sq.ft. price appreciation corridors in the NCR over the last decade"],
        whyInvestHi=["भारत का पहला LEED प्लेटिनम-प्रमाणित लक्ज़री रेजिडेंशियल प्रोजेक्ट",
                     "लेक-फेसिंग रेजिडेंस, वास्तुकार हाफ़िज़ कॉन्ट्रैक्टर की बंगला-शैली डिज़ाइन",
                     "रॉकवेल ग्रुप (न्यूयॉर्क) द्वारा इंटीरियर; आस-पास आर्नोल्ड पामर और गैरी प्लेयर के गोल्फ कोर्स",
                     "पिछले एक दशक में एनसीआर के सबसे तेज़ प्रति वर्ग फुट मूल्य वृद्धि वाले कॉरिडोर में से एक"],
        amenitiesEn=["Luxury clubhouse & concierge", "Lake-facing landscaped grounds", "Swimming pool & party lawns", "Children's play areas"],
        amenitiesHi=["लक्ज़री क्लबहाउस और कॉन्सियर्ज", "लेक-फेसिंग लैंडस्केप्ड ग्राउंड", "स्विमिंग पूल और पार्टी लॉन", "बच्चों के खेलने के क्षेत्र"],
        units=[dict(type="4 BHK", typeHi="4 बीएचके", size="6,900–7,400", priceCr=25),
               dict(type="5 BHK", typeHi="5 बीएचके", size="8,600–9,200", priceCr=35),
               dict(type="Penthouse", typeHi="पेंटहाउस", size="12,000+", priceCr=65)],
        heroArt="tower",
    ),
    dict(
        slug="assagao", cityEn="Goa", cityHi="गोवा",
        areaEn="Assagao", areaHi="असगांव",
        name="Villa Bella Piante, by Isprava", developerEn="Isprava", developerHi="इस्प्रावा",
        taglineEn="A holiday home that pays its own way.", taglineHi="एक हॉलिडे होम जो अपना खर्च खुद निकाले।",
        descriptionEn="In Assagao's Bouta Waddo, among paddy fields and heritage Portuguese-era lanes, Isprava's Villa Bella Piante blends contemporary luxury with timeless Goan design — ten minutes from Anjuna and Vagator.",
        descriptionHi="असगांव के बौता वाडो में, धान के खेतों और पुरानी पुर्तगाली-युग की गलियों के बीच, इस्प्रावा की विला बेला पियांटे समकालीन लक्ज़री को कालातीत गोवा शैली के साथ जोड़ती है — अंजुना और वागाटोर से दस मिनट की दूरी पर।",
        whyInvestEn=["10 minutes from Anjuna and Vagator, Goa's highest short-term rental demand zones",
                     "Assagao remains one of North Goa's most protected, low-density neighbourhoods",
                     "Isprava is one of Goa's most established names in architecturally designed luxury villas",
                     "Private pool and garden, with managed rental options available through Isprava"],
        whyInvestHi=["अंजुना और वागाटोर से 10 मिनट, गोवा के सबसे ज़्यादा शॉर्ट-टर्म रेंटल डिमांड वाले इलाके",
                     "असगांव अब भी उत्तर गोवा के सबसे संरक्षित, कम घनत्व वाले इलाकों में से एक है",
                     "इस्प्रावा गोवा के आर्किटेक्ट-डिज़ाइन लक्ज़री विला में सबसे स्थापित नामों में से एक है",
                     "प्राइवेट पूल और गार्डन, इस्प्रावा के ज़रिए मैनेज्ड रेंटल विकल्प उपलब्ध"],
        amenitiesEn=["Private swimming pool", "Landscaped garden", "Contemporary interiors with Goan-Portuguese detailing", "Managed rental program"],
        amenitiesHi=["प्राइवेट स्विमिंग पूल", "लैंडस्केप्ड गार्डन", "गोवा-पुर्तगाली डिटेलिंग के साथ समकालीन इंटीरियर", "मैनेज्ड रेंटल प्रोग्राम"],
        units=[dict(type="3 BR Villa", typeHi="3 बेडरूम विला", size="2,800–3,400", priceCr=4.5),
               dict(type="4 BR Villa", typeHi="4 बेडरूम विला", size="3,800–4,500", priceCr=6.2)],
        heroArt="villa",
    ),
    dict(
        slug="jubilee-hills", cityEn="Hyderabad", cityHi="हैदराबाद",
        areaEn="Jubilee Hills", areaHi="जुबली हिल्स",
        name="Phoenix Halcyon", developerEn="Phoenix Group", developerHi="फीनिक्स ग्रुप",
        taglineEn="Old-money address, new-city pace.", taglineHi="पुराना रुतबा, नए शहर की रफ़्तार।",
        descriptionEn="Spread over 5 acres in Hyderabad's Central Zone near Jubilee Hills, Phoenix Halcyon offers 156 residences across 3, 4 and 5 BHK configurations with smart-home automation, in a neighbourhood that has anchored Hyderabad's premium address market for decades.",
        descriptionHi="जुबली हिल्स के पास हैदराबाद के सेंट्रल ज़ोन में 5 एकड़ में फैला, फीनिक्स हैल्सियन 3, 4 और 5 बीएचके कॉन्फ़िगरेशन में स्मार्ट-होम ऑटोमेशन के साथ 156 रेजिडेंस प्रदान करता है, उस इलाके में जिसने दशकों से हैदराबाद के प्रीमियम पता बाज़ार को थामे रखा है।",
        whyInvestEn=["Central Zone location, close to HITEC City and the Financial District",
                     "156 residences across 5 acres — a boutique-scale premium development",
                     "Smart-home automation and premium specifications across all configurations",
                     "Jubilee Hills remains Hyderabad's most established premium address"],
        whyInvestHi=["सेंट्रल ज़ोन में स्थान, हाईटेक सिटी और फाइनेंशियल डिस्ट्रिक्ट के करीब",
                     "5 एकड़ में 156 रेजिडेंस — एक बुटीक स्तर का प्रीमियम विकास",
                     "सभी कॉन्फ़िगरेशन में स्मार्ट-होम ऑटोमेशन और प्रीमियम स्पेसिफिकेशन",
                     "जुबली हिल्स आज भी हैदराबाद का सबसे स्थापित प्रीमियम पता है"],
        amenitiesEn=["Smart-home automation", "Clubhouse with pool", "Landscaped central courtyard", "24-hour power backup & security"],
        amenitiesHi=["स्मार्ट-होम ऑटोमेशन", "पूल के साथ क्लबहाउस", "लैंडस्केप्ड सेंट्रल कोर्टयार्ड", "24 घंटे पावर बैकअप और सुरक्षा"],
        units=[dict(type="3 BHK", typeHi="3 बीएचके", size="2,400–2,800", priceCr=3.4),
               dict(type="4 BHK", typeHi="4 बीएचके", size="3,200–3,700", priceCr=4.8),
               dict(type="5 BHK", typeHi="5 बीएचके", size="4,200+", priceCr=6.5)],
        heroArt="tower",
    ),
    dict(
        slug="koregaon-park", cityEn="Pune", cityHi="पुणे",
        areaEn="Koregaon Park", areaHi="कोरेगांव पार्क",
        name="Godrej Koregaon Park", developerEn="Godrej Properties", developerHi="गोदरेज प्रॉपर्टीज",
        taglineEn="Tree-lined lanes, city-centre convenience.", taglineHi="हरे-भरे रास्ते, शहर के बीचों-बीच सुविधा।",
        descriptionEn="Spanning 4 acres in Pune's most prestigious neighbourhood, Godrej Koregaon Park offers premium residences close to Lane 7's restaurants and the Mula-Mutha riverfront, minutes from Pune's business districts and the airport.",
        descriptionHi="पुणे के सबसे प्रतिष्ठित इलाके में 4 एकड़ में फैला, गोदरेज कोरेगांव पार्क लेन 7 के रेस्तरां और मुला-मुठा रिवरफ्रंट के करीब प्रीमियम रेजिडेंस प्रदान करता है, पुणे के बिज़नेस डिस्ट्रिक्ट और एयरपोर्ट से कुछ ही मिनट की दूरी पर।",
        whyInvestEn=["Minutes to Pune Airport and the Koregaon Park business belt",
                     "Among Pune's greenest, most established residential lanes",
                     "Walking distance to Lane 7's restaurant and boutique scene",
                     "Strong, steady rental demand from Pune's corporate and expat community"],
        whyInvestHi=["पुणे एयरपोर्ट और कोरेगांव पार्क बिज़नेस बेल्ट से कुछ ही मिनट",
                     "पुणे की सबसे हरी-भरी, सबसे स्थापित रिहायशी गलियों में से एक",
                     "लेन 7 के रेस्तरां और बुटीक सीन से पैदल दूरी",
                     "पुणे के कॉर्पोरेट और प्रवासी समुदाय से मज़बूत, स्थिर किराया मांग"],
        amenitiesEn=["Landscaped grounds", "Clubhouse & swimming pool", "Riverfront proximity", "24-hour concierge & security"],
        amenitiesHi=["लैंडस्केप्ड ग्राउंड", "क्लबहाउस और स्विमिंग पूल", "रिवरफ्रंट से नज़दीकी", "24 घंटे कॉन्सियर्ज और सुरक्षा"],
        units=[dict(type="2 BHK", typeHi="2 बीएचके", size="950–1,150", priceCr=2.3),
               dict(type="3 BHK", typeHi="3 बीएचके", size="1,363–1,700", priceCr=3.99),
               dict(type="4 BHK", typeHi="4 बीएचके", size="2,000–2,400", priceCr=5.99)],
        heroArt="tower",
    ),
]

print(f"{len(PROPERTIES)} properties loaded")
